create_clock -period 20.000 -name clk [get_ports clk]

set_property PACKAGE_PIN AB18 [get_ports {seg[0]}]
set_property PACKAGE_PIN U17 [get_ports {seg[1]}]
set_property PACKAGE_PIN U18 [get_ports {seg[2]}]
set_property PACKAGE_PIN P14 [get_ports {seg[3]}]
set_property PACKAGE_PIN R14 [get_ports {seg[4]}]
set_property PACKAGE_PIN R18 [get_ports {seg[5]}]
set_property PACKAGE_PIN T18 [get_ports {seg[6]}]
set_property PACKAGE_PIN N17 [get_ports {seg[7]}]

set_property PACKAGE_PIN AA18 [get_ports {an[0]}]
set_property PACKAGE_PIN W17 [get_ports {an[1]}]
set_property PACKAGE_PIN V17 [get_ports {an[2]}]
set_property PACKAGE_PIN AB20 [get_ports {an[3]}]
set_property PACKAGE_PIN AA19 [get_ports {an[4]}]
set_property PACKAGE_PIN V19 [get_ports {an[5]}]
set_property PACKAGE_PIN V18 [get_ports {an[6]}]
set_property PACKAGE_PIN Y19 [get_ports {an[7]}]

set_property PACKAGE_PIN E3 [get_ports reset_n]
set_property PACKAGE_PIN Y18 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]

set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {an[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]

set_property -dict {PACKAGE_PIN M21  IOSTANDARD LVCMOS33} [get_ports {row[0]}]
set_property -dict {PACKAGE_PIN J20  IOSTANDARD LVCMOS33} [get_ports {row[1]}]
set_property -dict {PACKAGE_PIN J19  IOSTANDARD LVCMOS33} [get_ports {row[2]}]
set_property -dict {PACKAGE_PIN K18  IOSTANDARD LVCMOS33} [get_ports {row[3]}]
set_property -dict {PACKAGE_PIN K21  IOSTANDARD LVCMOS33} [get_ports {col[0]}]
set_property -dict {PACKAGE_PIN H20  IOSTANDARD LVCMOS33} [get_ports {col[1]}]
set_property -dict {PACKAGE_PIN J22  IOSTANDARD LVCMOS33} [get_ports {col[2]}]
set_property -dict {PACKAGE_PIN H17  IOSTANDARD LVCMOS33} [get_ports {col[3]}]

set_property PACKAGE_PIN T4 [get_ports sck]
set_property IOSTANDARD LVCMOS33 [get_ports sck]
set_property PACKAGE_PIN T5 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property PACKAGE_PIN W6 [get_ports dc_out]
set_property IOSTANDARD LVCMOS33 [get_ports dc_out]
set_property PACKAGE_PIN W5 [get_ports cs]
set_property IOSTANDARD LVCMOS33 [get_ports cs]
set_property PACKAGE_PIN U5 [get_ports reset_oled]
set_property IOSTANDARD LVCMOS33 [get_ports reset_oled]

set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {key3}]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports {key2}]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports {key1}]

set_property -dict {PACKAGE_PIN AA6 IOSTANDARD LVCMOS33} [get_ports {led}]